#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: asia.gcr.io/apt-retina-374510/china_gcp_learning # 変更箇所 DOCKERHUB_REPO_NAME
  tag: 3fbb2df58470519445bfb4a04e0a6d579fca919f

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer
